Revert "- movieplayer: allow screenshots from stream"
- sh4 build not ok

"/build_source/neutrino-mp-ddt/src/gui/movieplayer.cpp:3524:9: error: 'put_time' is not a member of 'std'
ss << std::put_time(&tm, "%Y%m%d_%H%M%S");"

This reverts commit 3eb26c838b0e4a4387ddda3b6e315e5351d2462f.